FROM python:3.12-slim
WORKDIR /app
COPY backend/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY backend /app
ENV CALC_SERVER_URL=http://calc:8770
ENV FLIGHT_SERVER_URL=http://flights:8771
ENV HOTEL_SERVER_URL=http://hotels:8772
ENV DESTINATION_SERVER_URL=http://destinations:8773
EXPOSE 8000
CMD ["uvicorn","main:app","--host","0.0.0.0","--port","8000"]
