FROM node:20-alpine AS build
WORKDIR /app
COPY frontend/package*.json ./
RUN npm ci
COPY frontend ./
RUN npm run build

FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app ./
EXPOSE 3000
CMD ["npm","run","start","--","-p","3000","-H","0.0.0.0"]


ENV HOST=0.0.0.0
ENV PORT=3000
EXPOSE 3000
# Si usas Next:
# CMD ["npm","run","start","--","-p","3000","-H","0.0.0.0"]
