version: '3.9'

services:
  backend:
    build: ./backend
    container_name: chat-multiagent-clean2-backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - mcp_flight_server
      - mcp_hotel_server
      - mcp_calc_server
      - mcp_destination_server
    networks:
      - appnet

  frontend:
    build: ./frontend
    container_name: chat-multiagent-clean2-frontend
    command: npm run dev
    ports:
      - "3000:3000"
    networks:
      - appnet

  mcp_flight_server:
    build: ./mcp_flight_server
    container_name: chat-multiagent-clean2-mcp_flight_server
    command: uvicorn server:app --host 0.0.0.0 --port 8771
    ports:
      - "8771:8771"
    networks:
      - appnet

  mcp_hotel_server:
    build: ./mcp_hotel_server
    container_name: chat-multiagent-clean2-mcp_hotel_server
    command: uvicorn server:app --host 0.0.0.0 --port 8772
    ports:
      - "8772:8772"
    networks:
      - appnet

  mcp_calc_server:
    build: ./mcp_calc_server
    container_name: chat-multiagent-clean2-mcp_calc_server
    command: uvicorn server:app --host 0.0.0.0 --port 8770
    ports:
      - "8770:8770"
    networks:
      - appnet

  mcp_destination_server:
    build: ./mcp_destination_server
    container_name: chat-multiagent-clean2-mcp_destination_server
    command: uvicorn server:app --host 0.0.0.0 --port 8773
    ports:
      - "8773:8773"
    networks:
      appnet:
        aliases:
          - destinations
          - mcp_destination_server

networks:
  appnet:
    driver: bridge
